Première page statique : hello opt-nc
adriens/temps-attente-streamlit pull request #17
Opened 2024-09-23 07:17 UTC by MalcolmBrt

Fixes
- #8

2024-09-23 10:03 UTC, adriens commented
@MalcolmBrt : je teste :zap:

2024-09-23 10:19 UTC, adriens commented
:bulb: j'ai aussi remappé les ports pour avoir un port plus standard : check le mapping des ports.
Au final ça simplifie la vie de deux qui vont déployer : 
![image](https://github.com/user-attachments/assets/4c89e197-c6d8-4f66-87d2-6dc3a2da44ea)

2024-09-23 10:20 UTC, adriens commented
@MalcolmBrt ; tu veux pousser un logo OPT et UNC ?... où on merge ?

2024-09-23 10:26 UTC, adriens commented
POUr injecter les logos, faut les stocker en ressources statiques au projet puis : 

```python
# Display the logo
st.image("path_to_logo_image.png", width=150)
```

2024-09-23 10:27 UTC, adriens requested changes
Ajuter les logos :pray:

2024-09-23 10:27 UTC, adriens commented on README.md
@MalcolmBrt , j'ai simplifié le `markdown` du procesus d'install, j'ai fixé un petit oubli et testé le tout : 
![image](https://github.com/user-attachments/assets/af092f0b-22f6-4bfa-be59-6bd77aaf3f5d)

2024-09-23 21:30 UTC, adriens commented
@MalcolmBrt , en fait on pourrait faire d'une pierre  deux coups : 

- Affiche logos OPT et UNC : gestion des assets statiques
- Afficher la date courant date/heure sur la page
- Activer l'autorefresh (cf #5 )... et voir la date/heure changer

2024-09-23 21:42 UTC, MalcolmBrt commented
Ok je vais m'en occuper

2024-09-23 21:48 UTC, adriens commented
> Ok je vais m'en occuper

Top, je pense que ça va aller très vite :thought_balloon:

2024-09-23 23:25 UTC, MalcolmBrt commented
Voici la version amélioré avec l'affichage des images, la date et l'heure puis l'autorefresh.
Ce qui donne :
![image](https://github.com/user-attachments/assets/c3dbe4b6-c9b6-46af-b338-5ec5026a2639)

2024-09-24 01:04 UTC, adriens commented
je teste ça

2024-09-24 01:06 UTC, adriens commented
Je lance l'app : 
![image](https://github.com/user-attachments/assets/c4eccd16-de10-4e62-9f70-8baab194fbbc)

2024-09-24 01:06 UTC, adriens commented
j'attends :long_drum:

2024-09-24 01:07 UTC, adriens commented
![image](https://github.com/user-attachments/assets/71cbac07-4fba-4e5c-ab57-407c0efc9fe0)

2024-09-24 01:09 UTC, adriens approved these changes
:ok_man: 
Faudrait faire une issue qui prenne en charge : 
- favicon
- un titre autre que "app"

![image](https://github.com/user-attachments/assets/941a3b96-926e-4b87-a237-a65d3321bfad)

2024-09-24 01:09 UTC, merged