ajout favicon et changement titre page #19
adriens/temps-attente-streamlit pull request #20
Opened 2024-09-25 10:23 UTC by morgancarre

fixes
- #19

2024-09-25 10:27 UTC, morgancarre commented
![image](https://github.com/user-attachments/assets/1741eacf-8de7-4f78-b49e-de076f0ee032)
l'auto-refresh n'interfère pas avec le titre et l'icone de la page.

2024-09-25 21:17 UTC, adriens requested changes
le favico est censé donner une idée de ce que l'on va consommer.
Dans notre cas, c'est un temps d'attente dans une Agence de l'OPT-NC
Or on voit le logo de l'UNC : c'est confusant
**:point_right: Basculer vers le logo de l'OPT-NC est plus adapté**

:bulb: Pour mettre en avant que c'est un travail collaboratif UNC/OPT-NC, on peut prévoir une page About qui détaillera la nature de l'organisation et même l'url de cette repo publique :thought_balloon:

2024-09-26 02:30 UTC, adriens commented
hello @morgancarre , je vais pas avoir le temps de démarrer le code cet aprem : tu peux me dropper un screenshot du rendu stp ?

2024-09-26 02:37 UTC, morgancarre commented
Bien sur, voilà le rendu : 
![Capture d’écran 2024-09-26 133643](https://github.com/user-attachments/assets/02b82350-7a3a-4a87-adb9-574ecc33f391)

2024-09-26 02:54 UTC, adriens commented
Preque OK alors, je crois que c'est le moment de mettre un vrai titre (au lieu de _Hello OPT-NC_) : mettre par exemple : 

_Temps d'attente en agence OPT-NC_

2024-09-26 03:08 UTC, morgancarre commented
Bien reçu, je modifie tout de suite

2024-09-26 03:12 UTC, morgancarre commented
Voilà le résultat : 
![Capture d'écran 2024-09-26 141207](https://github.com/user-attachments/assets/ae9ce413-6ee4-4135-bb9a-ce9cc04f2318)

2024-09-26 03:38 UTC, adriens approved these changes
👍

2024-09-26 03:38 UTC, merged

2024-09-26 03:39 UTC, adriens commented
💡 Après, on pourra mettre le nom de l'agence en cours par exemple...