Clé API dans variable environnement
adriens/temps-attente-streamlit pull request #25
Opened 2024-09-26 07:32 UTC by MalcolmBrt

Fixes
- #24 
J'en ai également profité pour réorganiser un peu les fonctions utilitaires dans un autre fichier.

2024-09-26 07:57 UTC, adriens commented
Je regarde tout ça tout à l'heure

2024-09-26 09:59 UTC, adriens requested changes
Pour l'API Key,il faut que son nom donne une indication car à terme dans le fichier .env, il peux y en avoir bcp d'autres

Par exemple ici : https://github.com/opt-nc/mobitag/blob/main/mobitag.go

Dans l'env on stocke ceci : `OPTNC_MOBITAGNC_API_KEY`


et pour le header, là ce sera forcément l'équivalent de ceci : 

```go
// set request headers
req.Header.Set("Content-Type", "application/json")
// Authenticate the request
req.Header.Set("x-apikey", mobitagAPIKey)
```

2024-09-26 23:52 UTC, adriens commented
@morgancarre  a testé sur sa machine : 'est OK donc à lui de merger :rocket:

2024-09-26 23:54 UTC, adriens commented
:hand: @morgancarre faut bien veiller à prendre en considration le renommage de la variable car `return os.getenv("APIKEY")` est pas suffisant cf mon non-approve de cette PR @MalcolmBrt

2024-09-26 23:57 UTC, MalcolmBrt commented
Juste, je n'ai pas encore fait les changements par rapport au nom de la variable. Je m'en occupe cette après midi et il pourra merge

2024-09-27 01:25 UTC, adriens commented
Excellent 
Bravo les gars pour la collaboration, la synchronisation des actions et la réactivité 
C'est du bon boulot bien efficace

2024-09-27 05:53 UTC, MalcolmBrt commented
J'ai modifié le nom de la variable en WAITINGTIME_APIKEY.
J'ai pas pensé à mettre OPTNC dans le nom mais ça reste assez explicite selon moi.
@morgancarre tu peux check de ton côté et merge stp ?

2024-09-27 19:31 UTC, adriens commented
> J'ai modifié le nom de la variable en WAITINGTIME_APIKEY.
> J'ai pas pensé à mettre OPTNC dans le nom mais ça reste assez explicite selon moi.

:point_up: Imagine que quelqu'un débarque et tombe sur cette clé : comment peut-il deviner qu'il s'agit de l'OPT-NC ?

2024-09-28 02:29 UTC, MalcolmBrt commented
Je viens de rajouter cela.

2024-09-28 02:56 UTC, adriens commented
> Je viens de rajouter cela.

je :eyes:

2024-09-28 02:57 UTC, adriens approved these changes
Let's go :rocket:

2024-09-28 02:57 UTC, adriens commented on utils.py
Yes, ça c bien clair. :+1:

2024-09-28 02:57 UTC, merged