Ajout menu déroulant communes et agences #21
adriens/temps-attente-streamlit pull request #30
Opened 2024-09-30 05:46 UTC by morgancarre

fixes
- #21 

- ajout de la barre latérale pour sélection commune et agence
- ajout menu déroulant communes
- ajout menu déroulant agences

2024-09-30 07:21 UTC, adriens commented
@morgancarre , tu dois bien positionner les assignee et les bons labels stp : 
![image](https://github.com/user-attachments/assets/20acba76-711d-4edb-a406-e0d0fff88e3e)

2024-09-30 07:24 UTC, adriens requested changes
Le code ci-dessous n'est pas optimal : 

```python
api_url_communes = "https://api.opt.nc/temps-attente-agences/communes"
api_url_agences = "https://api.opt.nc/temps-attente-agences/agences"
```

Il faudrait plutôt passer par une constante genre `API_TEMPS_ATTENTE_BASE_URL` = `https://api.opt.nc/temps-attente-agences/`

Puis dans les appels ajouter `/communes` ou `agences` selon les besoins.

2024-09-30 23:25 UTC, MalcolmBrt commented
J'ai testé de mon côté sur ubuntu avec l'image docker, ça fonctionne correctement.
![image](https://github.com/user-attachments/assets/b52922e6-be45-45e1-9005-35577a8c89d0)

2024-10-02 08:07 UTC, adriens approved these changes
Hello les gars, désolé pour les feedbacks un peu lents ces deux derniers jours, grosses journées et la machine que j'utilise le soir m'a lâché... mais y'a du bon car maintenant...

![image](https://github.com/user-attachments/assets/6ff0f173-472d-4253-aed0-85aea2e1a6f0)

2024-10-02 08:07 UTC, merged